version: '3.8'
services:
  api:
    container_name: api-kahoot
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
#    ports:
#      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=${DB_DATABASE}
      - DB_USERNAME='postgres'
      - DB_SYNC=1

volumes:
  data: {}